arb-dir: lib/core/l10n
template-arb-file: app_vi.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/l10n
untranslated-messages-file: untranslated.txt