// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-hjFiU_nDoHhLu4S6AY-8KoYAP7v7q4g',
    appId: '1:875593479035:web:5faeae3be1e9d3f94203de',
    messagingSenderId: '875593479035',
    projectId: 'task-expense-manager',
    authDomain: 'task-expense-manager.firebaseapp.com',
    storageBucket: 'task-expense-manager.firebasestorage.app',
    measurementId: 'G-G4JJNGYSD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMz4B1JkU3iqLan7Ynx_KKjF8xQUdGPo',
    appId: '1:875593479035:android:35820027bf21317b4203de',
    messagingSenderId: '875593479035',
    projectId: 'task-expense-manager',
    storageBucket: 'task-expense-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLdYO39Vb--JPmZwyVlc--k0MJAUF0pdI',
    appId: '1:875593479035:ios:a6798259f8b0d5b74203de',
    messagingSenderId: '875593479035',
    projectId: 'task-expense-manager',
    storageBucket: 'task-expense-manager.firebasestorage.app',
    iosBundleId: 'com.example.taskExpenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-hjFiU_nDoHhLu4S6AY-8KoYAP7v7q4g',
    appId: '1:875593479035:web:ca6ca7d174189a584203de',
    messagingSenderId: '875593479035',
    projectId: 'task-expense-manager',
    authDomain: 'task-expense-manager.firebaseapp.com',
    storageBucket: 'task-expense-manager.firebasestorage.app',
    measurementId: 'G-CHE5HCT378',
  );
}
